### ISSUE TITLE
Message listeners on datastore change

### ISSUE THREAD

**Issue by bdfoster** [onehilltech/blueprint#16]
Resource controllers could be made to emit an event whenever the underlying datastore has been modified, so that listeners can easily react to this change (via PUT, POST, DELETE, etc. but not GET HTTP methods).

Event data for create/update operations should include the updated or created document, while delete operations should include the deleted document.

The namespace of the event could be constructed like:
```
namespace = opts.prefix || 'resource' + '.' + collection_name + '.' + datastore_operation
```
...then, using blumate.messaging API, emit the event for consumption by listeners.

I'll go ahead and work up a PR if you're on board. Any suggestions or feedback would be great.

**Comment by hilljh82** [comment]
We will add event notifications for resource creating, update, and deletion, for now. The event will have the following naming convention:

    [prefix.]<resource_name>.<action>

where `prefix` is a user-defined prefix to prevent name clashing of events. `resource_name` is the name of the resource given at construction time for the `ResourceController`. `action` is the database action that occurred. The value of action is one of the following:

* created
* updated
* deleted

You can register for an event by adding the appropriate listener to `app/listeners`. For example, if you wanted to listed for the creation of the book resource assuming a prefix of test, then you would add a listeners to `app/listeners/test.book.created`.
