### ISSUE TITLE
How are partial views implemented?

### ISSUE THREAD

**Issue by bdfoster** [onehilltech/blueprint#29]
Partial views (such as with handlebars) do not seem to be supported, but is a key element in the DRY (don't repeat yourself) principle. Is there a directory (or a way to configure a directory) where partial views can be imported into a parent view? 

On that same line of thinking, is there a directory (...) where layouts can be created/specified in a view?

**Comment by hilljh82** [comment]
@bdfoster It seems as if someone else had this issue with Express, and has created a [new project](https://github.com/ericf/express-handlebars) to better support partials views in handlebars. 

Will this project solve your problem? 

If so, then we have add a `engine` property to the `server.config.js`. This should allow you to integrate [express-handlebars](https://github.com/ericf/express-handlebars).

**Comment by bdfoster** [comment]
I did find that when searching Google. It definitely would solve the problem, but only for handlebars.

I agree, adding support for custom view engines would be beneficial. Picking up on #30.

**Comment by hilljh82** [comment]
Closing this question.
