### ISSUE TITLE
Validate.js

### ISSUE THREAD

**Issue by bdfoster** [onehilltech/blueprint#31]
It would be nice to integrate [Validate.js](https://validatejs.org) (possibly by module), as a way to validate requests. This could be the basis of a "request model", making the use of Mongoose in blueprint-mongodb optional.

**Comment by hilljh82** [comment]
This seems interesting, and worth looking into. As for validation via mongoose in blueprint-mongodb, it will always need to be there. You have cases where you may store data in the database that is not generated by a request. This would potentially replace `express-validate`. The only problem with this validation engine is that it is not easy to express where the validation is to occur (i.e., body, query, or params). This is one advantage of using `express-validate`.

**Comment by hilljh82** [comment]
We are going to update Blueprint to implements its on validation framework instead of using `express-validator`. This will overcome several shortcomings of `express-validator` and allow you to use custom validation frameworks, such as [Validate.js](https://validatejs.org)
