### ISSUE TITLE
Socket.io

### ISSUE THREAD

**Issue by cotz1995** [onehilltech/blueprint#39]
It would be awesome to integrate Socket.io for sending events to and from clients. I currently have it working in the following way: 

`var io = null;`
`blueprint.messaging.on('app.init', function (app) {`
`    io = require ('socket.io')(app.server._protocols[0]._protocol);`
`});`

**Comment by hilljh82** [comment]
@cotz1995 This would be a good module to add to the `Blueprint` ecosystem. There will need to be some updates, but we can look at adding this as a module. We will update this issue as progress is made.

Your current approach works for now.

**Comment by hilljh82** [comment]
The first implementation of blueprint-socket.io is available:

  https://github.com/onehilltech/blueprint-socket.io
