### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'lookup')

### ISSUE THREAD

**Issue by caturhidayat** [onehilltech/blueprint#57]
I started the server `node ./app`, server already running, but if i access http://localhost:8080/ has some error like on title

**Comment by hilljh82** [comment]
@caturhidayat The current workaround for this issue is to manually run `npm install` from the root directory of the blueprint project. Please let me know if this resolves your problem.

**Comment by caturhidayat** [comment]
after doing `npm install`i get error like this : 

> Severity: moderate
> Memory Exposure in tunnel-agent - https://github.com/advisories/GHSA-xc7v-wxcw-j472
> No fix available
> node_modules/npm/node_modules/request/node_modules/tunnel-agent
> 
> 30 vulnerabilities (2 low, 10 moderate, 13 high, 5 critical)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> Some issues need review, and may require choosing
> a different dependency.

 I try to fix this using `npm audit fic --force`, but still errors

> tar  <=4.4.17
> Severity: high
> Arbitrary File Overwrite in tar - https://github.com/advisories/GHSA-j44m-qm6p-hp7m
> Arbitrary File Creation/Overwrite on Windows via insufficient relative path sanitization - https://github.com/advisories/GHSA-5955-9wpr-37jh
> Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links - https://github.com/advisories/GHSA-qq89-hq3f-393p
> Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning using symbolic links - https://github.com/advisories/GHSA-9r2w-394v-53qc
> Arbitrary File Creation/Overwrite due to insufficient absolute path sanitization - https://github.com/advisories/GHSA-3jfq-g458-7qm9
> Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning - https://github.com/advisories/GHSA-r628-mhmh-qjhw
> No fix available
> node_modules/npm/node_modules/tar
>   node-gyp  <=3.8.0
>   Depends on vulnerable versions of tar
>   node_modules/npm/node_modules/node-gyp
> 
> tough-cookie  <2.3.3
> Severity: high
> Regular Expression Denial of Service in tough-cookie - https://github.com/advisories/GHSA-g7q5-pjjr-gqvp
> fix available via `npm audit fix`
> node_modules/npm/node_modules/request/node_modules/tough-cookie

**Comment by caturhidayat** [comment]
@hilljh82 like this  ![CleanShot 2022-07-07 at 19 48 48@2x](https://user-images.githubusercontent.com/94335744/177777223-af063d99-afbb-4352-8eaf-5fb2334d64e0.png)

**Comment by hilljh82** [comment]
@caturhidayat I'm having a hard time reproducing this error on my MacBook. Do you have a public repo for the example project that I can use to investigate the problem more?

**Comment by caturhidayat** [comment]
@hilljh82 you can access in [here](https://github.com/caturhidayat/bp-helloworld)

**Comment by hilljh82** [comment]
@caturhidayat I added the missing blueprint module

    npm install @onehilltech/blueprint@^4.0.0 --save

and everything starts on my machine:

**Comment by caturhidayat** [comment]
Hay @hilljh82 , thank you for your response. after add `npm install @onehilltech/blueprint@^4.0.0 --save`, code running well... 🎉
