### ISSUE TITLE
Initial creation requires a models folder

### ISSUE THREAD

**Issue by stretch1414** [onehilltech/blueprint#9]
The initial creation of an app with blueprint seems to be expecting a "models" folder to exist, which is not necessarily created from blueprint-init.  The error is coming from fs.js:856 when it is trying to read the directory (which is being called from the blueprint Application.js:59:9).  This is bring thrown when I try to do a "node ./app" to start the application.

**Comment by hilljh82** [comment]
Just push a new beta version out. It should resolve this problem.

**Comment by stretch1414** [comment]
Verified working on v0.11.0
